ERP University Registration/project-8/Models/Cours.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project_8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cours
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cours()
        {
            this.Classes = new HashSet<Class>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> Major_id { get; set; }
        public Nullable<int> Classification_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class> Classes { get; set; }
        public virtual Classification Classification { get; set; }
        public virtual Major Major { get; set; }
    }
}

ERP University Registration/project-8/Controllers/CoursController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using project_8.Models;

namespace project_8.Controllers
{
    public class CourceViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Major { get; set; }
        public string Classification { get; set; }
    }
    public class CoursController : Controller
    {
        private project8Entities db = new project8Entities();

        // GET: Cours
        public ActionResult Index()
        {
            var courses = db.Courses.Include(c => c.Classification).Include(c => c.Major);
            return View(courses.ToList());
        }

        // GET: Cours/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cours cours = db.Courses.Find(id);
            if (cours == null)
            {
                return HttpNotFound();
            }
            return View(cours);
        }

        // GET: Cours/Create
        public ActionResult Create(string search)
        {
            ViewBag.Classification_id = new SelectList(db.Classifications, "Id", "Classification_Name");
            ViewBag.Major_id = new SelectList(db.Majors, "Id", "Name");

            if (search == null)
            {
                var result = from sc in db.Courses
                             select new CourceViewModel
                             {
                                 Id = sc.Id,
                                 Name = sc.Name,
                                 Major = sc.Major.Name,
                                 Classification = sc.Classification.Classification_Name
                             };
                var dataaa = result.ToList();
                ViewBag.Cours = dataaa;

            }
            else
            {
                var result = from sc in db.Courses
                             where sc.Name.Contains(search)
                             select new CourceViewModel
                             {
                                 Id = sc.Id,
                                 Name = sc.Name,
                                 Major = sc.Major.Name,
                                 Classification = sc.Classification.Classification_Name
                             };
                var dataaa = result.ToList();
                ViewBag.Cours = dataaa;



            }
           


            var data = db.Courses.ToList();
            ViewBag.Courses = data;
            return View();
        }

        // POST: Cours/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Major_id,Classification_id")] Cours cours)
        {
            if (ModelState.IsValid)
            {
                db.Courses.Add(cours);
                db.SaveChanges();
                return RedirectToAction("Create");
            }

            ViewBag.Classification_id = new SelectList(db.Classifications, "Id", "Classification_Name", cours.Classification_id);
            ViewBag.Major_id = new SelectList(db.Majors, "Id", "Name", cours.Major_id);
            return View(cours);
        }

        // GET: Cours/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cours cours = db.Courses.Find(id);
            if (cours == null)
            {
                return HttpNotFound();
            }
            ViewBag.Classification_id = new SelectList(db.Classifications, "Id", "Classification_Name", cours.Classification_id);
            ViewBag.Major_id = new SelectList(db.Majors, "Id", "Name", cours.Major_id);
            return View(cours);
        }

        // POST: Cours/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Major_id,Classification_id")] Cours cours)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cours).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Create");
            }
            ViewBag.Classification_id = new SelectList(db.Classifications, "Id", "Classification_Name", cours.Classification_id);
            ViewBag.Major_id = new SelectList(db.Majors, "Id", "Name", cours.Major_id);
            return View(cours);
        }

        // GET: Cours/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cours cours = db.Courses.Find(id);
            if (cours == null)
            {
                return HttpNotFound();
            }
            return View(cours);
        }

        // POST: Cours/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cours cours = db.Courses.Find(id);
            db.Courses.Remove(cours);
            db.SaveChanges();
            return RedirectToAction("Create");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ERP University Registration/project-8/Views/Cours/Create.cshtml
@model project_8.Models.Cours

@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Cours</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2", style = "text-align: left;width: 150px;" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class="control-label col-md-2" style="text-align:left;width:150px;" for="Major_id">Major</label>

                <div class="col-md-10">
                    @Html.DropDownList("Major_id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Major_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Classification_id, "Classification_id", htmlAttributes: new { @class = "control-label col-md-2", style = "text-align: left;width: 150px;" })
                <div class="col-md-10">
                    @Html.DropDownList("Classification_id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Classification_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }




    <br />
    <br />

    <div class="ser" style="width:100%;overflow:auto">
        @using (Html.BeginForm("Create", "Cours", FormMethod.Get))

        {
            @Html.TextBox("search")
            <input type="Submit" value="search" class="btn btn-light" />
        }
    </div><br />

    <table class="table table-striped">
        <tr>
            <th>
                <span>Name</span>

            </th>
            <th>
                <span>Major</span>

            </th>
            <th>
                <span>Classification</span>

            </th>
            <th></th>
        </tr>

        @foreach (var item in ViewBag.Cours)
        {
            <tr>
                <td>
                    <span>@item.Name</span>
                </td>
                <td>
                    <span>@item.Major</span>
                </td>
                <td>
                    <span>@item.Classification</span>
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-success" }) |

                    @Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger" })
                </td>
            </tr>
        }
    </table>



</body>
</html>

ERP University Registration/project-8/Views/Cours/Delete.cshtml
@model project_8.Models.Cours

@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Delete</title>
</head>
<body>
    <h3>Are you sure you want to delete this?</h3>
    <div>
        <h4>Cours</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Classification.Classification_Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Classification.Classification_Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Major.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Major.Name)
            </dd>
    
        </dl>
    
        @using (Html.BeginForm()) {
            @Html.AntiForgeryToken()
    
            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</body>
</html>

ERP University Registration/project-8/Views/Cours/Details.cshtml
@model project_8.Models.Cours

@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Details</title>
</head>
<body>
    <div>
        <h4>Cours</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Classification.Classification_Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Classification.Classification_Name)
            </dd>
    
            <dt>
                @Html.DisplayNameFor(model => model.Major.Name)
            </dt>
    
            <dd>
                @Html.DisplayFor(model => model.Major.Name)
            </dd>
    
        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

ERP University Registration/project-8/Views/Cours/Edit.cshtml
@model project_8.Models.Cours

@{
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Edit</title>
</head>
<body>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryval")
    
    
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>Cours</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)
    
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Major_id, "Major_id", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Major_id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Major_id, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                @Html.LabelFor(model => model.Classification_id, "Classification_id", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("Classification_id", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Classification_id, "", new { @class = "text-danger" })
                </div>
            </div>
    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

ERP University Registration/project-8/Views/Cours/Index.cshtml
@model IEnumerable<project_8.Models.Cours>

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Classification.Classification_Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Major.Name)
            </th>
            <th></th>
        </tr>
    
    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Classification.Classification_Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Major.Name)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Details", "Details", new { id=item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id=item.Id })
            </td>
        </tr>
    }
    
    </table>
</body>
</html>